services:
  maria-backup-maker:
    image: alanfzf/db-backup-maker:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./config/crontab
        target: /etc/crontab
        read_only: true
        bind:
           create_host_path: false
    extra_hosts:
      # this one is needed to connect to the host machine
      # from within the container
      - "host.docker.internal:host-gateway"
