name: build-and-push

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build container with Nix
        run: nix build

      - name: Install skopeo
        run: sudo apt-get update && sudo apt-get install -y skopeo

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          skopeo login docker.io \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: Push image to Docker Hub
        run: |
          skopeo copy \
            docker-archive:result \
            docker://docker.io/${{ secrets.DOCKERHUB_USERNAME }}/db-backup-maker:latest
